### ISSUE TITLE
Feature Request: Allow any type that implements syn::Parse as an input type

### ISSUE THREAD

**Issue by JustusFluegel** [ModProg/manyhow#10]
As I've added on stream I think something that would enable the following would be quite useful:

```rs
struct SomeInput {
...
}

impl syn::Parse for SomeInput {
...
}

#[manyhow(proc_macro)]
pub fn some_macro(input: SomeInput) -> manyhow::Result {
...
}
```

As discussed on stream it would probably be good to put that feature under the `syn` feature gate, maybe even a new one.

**Comment by ModProg** [comment]
it might be necessary to have an attribute for this, as only `proc_macro2::TokenStream` implements `Parse` but `proc_macro::TokenStream` does not.

Maybe the syntax would end up being:

```rs
#[manyhow(proc_macro)]
pub fn some_macro(#[parse] input: SomeInput) -> manyhow::Result {
  ...
}
```

An extension is to support any return type that implements `ToTokens` / `Result<impl ToTokens>`.

**Comment by ModProg** [comment]
We could also drop support for `proc_macro::TokenStream` but I'm not sure that I'm a fan of that, as e.g. `proc_macro_input` from syn only supports `TokenStream` IIRC.

**Comment by JustusFluegel** [comment]
If we had specialization we could add a new trait and impl it for T: ToTokens & proc_macro::TokenStream ¯\_(ツ)_/¯

**Comment by ModProg** [comment]
I asked for quote, let's see #265
