### ISSUE TITLE
What should happen if a function emitted errors but returns Ok

### ISSUE THREAD

**Issue by ModProg** [ModProg/manyhow#2]
1. when a macro returns Ok() ignore any emitted errors (to fail with a non empty emitter I'd have some method on emitter e.g. .fail_if_dirty() -> Result<!, Error>
2. when a macro returns Ok() and emitter is non empty return the Ok tokens but the errors emitted as well. To ignore emitted errors one would need to call .clear() on the emitter before returning.

**Comment by DCNick3** [comment]
I think the second variant makes sense here. Emitting dummy tokens even in case of errors helps with reducing noise from "missing declaration" errors and is actually a thing supported in `proc-macro-error` (through a different mechanism)

**Comment by ModProg** [comment]
There is also this for dummy tokens: https://docs.rs/manyhow/latest/manyhow/#dummy-mut-tokenstream that would even work when returning `Err`.

But IIRC I did implement the second option.

**Comment by DCNick3** [comment]
Another way to sort this out would be to make `Emitter::new()` public and to make it responsibility of the caller to handle it however they see fit (with a drop bomb attached). This would make it look a lot like [`darling::error::Accomulator`](https://docs.rs/darling/latest/darling/error/struct.Accumulator.html)

**Comment by ModProg** [comment]
I could add `Emitter::new()` and `Emitter::into_error() -> Result<(), Error>`. That should support your usecase

**Comment by DCNick3** [comment]
`Emitter::into_error()` should probably be called `Emitter::into_result()` :sweat_smile: 

Also, I think that re-using `Emitter` for two cases (emitting a silent error leaving the handling to the `manyhow` machinery and using it as an accumulator) creates non-orthogonality that can lead to confusion about which method should be called...

If you keep the "manyhow machinery" use-case I think it's better to create a separate type for this

**Comment by ModProg** [comment]
I think it would be possible to remove `fail_if_dirty` and replace it with `into_result`.

It would just need to be called on an `&mut` and would clear the `Emitter`.

Then, if you call `.into_result()` the errors are returned through that. If `.into_result()` is not called, the errors in the "main" `Emitter` are returned as they are currently.

**Comment by DCNick3** [comment]
Thanks!
