### ISSUE TITLE
Something went wrong with 0.5.0 release?

### ISSUE THREAD

**Issue by DCNick3** [ModProg/manyhow#8]
The `0.5.0` release uploaded to crates.io doesn't seem to correspond to the commit where the release was made..

It doesn't have the `darling` support, but has the `emit!` macro.

Also, the ref specified in `.cargo_vcs_info.json` (`f18549151de376251a0635f755596ec02c14972a`) does not correspond to any commit in `main` branch..

Did something go wrong with amending?

**Comment by ModProg** [comment]
Should work now with `0.5.1` not sure what was the cause
